# para obtener el barer token de firebase con el pryecto de node
GET localhost:3000

###

# no es lo recomendado usar esta forma pero es muy sencilla
POST https://fcm.googleapis.com/fcm/send

Content-Type: application/json
# Authorization: key de firebase
Authorization: 

    # to: el identificador del dispositivo
{
 "to" : "",
 "notification" : {
     "body" : "Desde Rest client visual",
     "title": "Hola mundo"
 },
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title",
     "key_1" : "Value for key_1",
     "key_2" : "Value for key_2"
 }
}

###
# forma recomenda (se recomienda mejor utilizar el sdk de firebase)
# projects/nombre del proyecto

POST https://fcm.googleapis.com/v1/projects/flutter-proyects-b8f31/messages:send

Content-Type: application/json
# Authorization: el bearer token que salio del get a localhost
Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA

# token: del dispositivo
{
   "message":{
      "token":"",
      "data":{
        "hola": "mundo",
        "hello": "world"
      },
      "notification":{
        "title":"FCM Message",
        "body":"This is an FCM notification message!"
      },
      "android": {
        "notification": {
          "image": "https://cdn.pixabay.com/photo/2018/02/21/05/17/cat-3169476_1280.jpg"
        }
      }
   }
}



