// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9XzPCzfpOIVktEVDGff0ANdwZWlRw6k',
    appId: '1:457993027386:web:8461c04260bb82a24b1a03',
    messagingSenderId: '457993027386',
    projectId: 'flutter-proyects-b8f31',
    authDomain: 'flutter-proyects-b8f31.firebaseapp.com',
    storageBucket: 'flutter-proyects-b8f31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIjQkBM7CmjViqsgQimRAbC4pKO5bATs',
    appId: '1:457993027386:android:d5776356fc6cf2794b1a03',
    messagingSenderId: '457993027386',
    projectId: 'flutter-proyects-b8f31',
    storageBucket: 'flutter-proyects-b8f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Bp6BOQUaGYWe6Ttd-W2kN8War2mUPUY',
    appId: '1:457993027386:ios:714327776ccf18af4b1a03',
    messagingSenderId: '457993027386',
    projectId: 'flutter-proyects-b8f31',
    storageBucket: 'flutter-proyects-b8f31.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Bp6BOQUaGYWe6Ttd-W2kN8War2mUPUY',
    appId: '1:457993027386:ios:c4ee0f7af89496ec4b1a03',
    messagingSenderId: '457993027386',
    projectId: 'flutter-proyects-b8f31',
    storageBucket: 'flutter-proyects-b8f31.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
